# Generated by Django 4.1.1 on 2022-09-14 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ngo",
            fields=[
                (
                    "_id",
                    models.AutoField(editable=False, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(blank=True, max_length=200, null=True)),
                ("location", models.CharField(blank=True, max_length=200, null=True)),
                ("desc", models.TextField(blank=True, null=True)),
                ("ngo_owner", models.CharField(blank=True, max_length=200, null=True)),
                ("startedAt", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="donor",
            fields=[
                ("name", models.CharField(blank=True, max_length=200, null=True)),
                ("dob", models.DateField(blank=True)),
                ("address", models.TextField(blank=True, null=True)),
                ("city", models.CharField(blank=True, max_length=200, null=True)),
                ("state", models.CharField(blank=True, max_length=200, null=True)),
                ("pincode", models.IntegerField(blank=True, null=True)),
                ("amount_donated", models.IntegerField(blank=True, null=True)),
                (
                    "father_s_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "mother_s_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "donation_message",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "_id",
                    models.AutoField(editable=False, primary_key=True, serialize=False),
                ),
                (
                    "ngo_donated",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="donated",
                        to="src.ngo",
                    ),
                ),
                (
                    "ngo_member",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="member",
                        to="src.ngo",
                    ),
                ),
            ],
        ),
    ]
