# Generated by Django 4.1.1 on 2022-11-11 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ngo',
            name='contact',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
