# Generated by Django 4.1.1 on 2023-01-17 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subscribedNgos',
            field=models.ManyToManyField(blank=True, null=True, to='src.ngo'),
        ),
    ]
