# Generated by Django 4.1.1 on 2022-11-11 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0002_ngo_tagline'),
    ]

    operations = [
        migrations.AddField(
            model_name='ngo',
            name='contact',
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
    ]
